#+title My Emacs Configuration
#+PROPERTY: header-args:emacs-lisp :tangle ./init.el

This is my personal emacs configuration as well as its documentation using org babel. Each code block is tangled with the init.el file.

Currenty, this leads to just one long init.el containing the code blocks of this file in order. Later, I might want to structure this into more sensible units.

This is work in progress, a lot can be improved.

Since the selection of Emacs packages is so enormous, there are some community-curated lists:

- https://github.com/emacs-tw/awesome-emacs

Emacs 31 has introduces warnings for not setting explicit cookies for [[https://www.gnu.org/software/emacs/manual/html_node/elisp/Lexical-Binding.html][lexical binding]] (deciding whether or not to use lexical binding or opt out and use dynamic binding). We explicitely opt in as is recommended. We also suppress the warning from external packages (since some have not been updated yet, leading to a warning on every startup).

#+begin_src emacs-lisp
  ;;; -*- lexical-binding: t; -*-
  (add-to-list 'warning-suppress-types '(files missing-lexbind-cookie))
#+end_src

* Path

For convenience, we start by setting some file system path related variables. [[elisp:(describe-variable 'user-emacs-directory)][user-emacs-directory]] contains the path assigned to the local Emacs installation.

#+begin_src emacs-lisp
  (defvar non-repo-lisp-packages-path (concat user-emacs-directory "lisp/"))
#+end_src


* Package Mangement

Before packages are even loaded, their management must be configured a little. The standard [[https://elpa.gnu.org][ELPA]] (Emacs Lisp Package Archive) repository is a bit barren in comparison. We add the very common additional repositories [[https://melpa.org][MELPA]] (Milkypostman's Emacs Lisp Package Archive) and the repo for the  infamous [[https://orgmode.org][Org]] package.

#+begin_src emacs-lisp
  (require 'package)

  (setq package-archives '(("elpa" . "https://elpa.gnu.org/packages/")
  			 ("melpa" . "https://melpa.org/packages/")
  			 ("org" . "https://orgmode.org/elpa/")))

  (package-initialize)
  (unless package-archive-contents
    (package-refresh-contents))

  ;; Initialize use-package on non-Linux platforms
  (unless (package-installed-p 'use-package)
    (package-install 'use-package))

  (require 'use-package)
  (setq use-package-always-ensure t)

  ;; Add local path to Emacs packages not managed by one of the repos above
  (add-to-list 'load-path non-repo-lisp-packages-path)
  (add-to-list 'load-path (concat non-repo-lisp-packages-path "assist_emacs")) ;; my own package
#+end_src


* General

This sections contains settings for how and where Emacs saves automatically generated files, deals with persisting the history, etc.

** No Littering

The package [[https://github.com/emacscollective/no-littering][No Littering]] helps keep the Emacs folders clean from automatically generated files. So far, this is just the default configuration and should be changed later.

#+begin_src emacs-lisp
  (use-package no-littering)
#+end_src

** Save History

With safehist, we ensure the minibuffer history is persisted.

#+begin_src emacs-lisp
  (use-package savehist
    :config
    (add-to-list 'savehist-additional-variables 'eww-history)
    (savehist-mode))
#+end_src

** Tab Bar

We can configure the way Emacs uses the tab system quiet extensively. For now, this just ensures that the [[Dashboard]] is shown in any new tab.

#+begin_src emacs-lisp
(setq tab-bar-new-tab-choice "*dashboard*")
#+end_src


* Appearence

This section contains everything regarding how Emacs looks.

The following are essentially infamous default settings.

#+begin_src emacs-lisp
  (toggle-frame-fullscreen)

  (tool-bar-mode 0)
  (menu-bar-mode 0)
  (scroll-bar-mode 0)
  (tooltip-mode 0)
  (display-time-mode 1)
  (set-fringe-mode 5)

  (setq inhibit-startup-screen t)
  (setq inhibit-startup-message t)
  (setq visible-bell t)
#+end_src

** Themes

Configurations for themes go here. I've tried themes from the [[https://github.com/doomemacs/themes][doom-themes]] and [[https://github.com/bbatsov/zenburn-emacs][zenburn]] packages. But for my current display (which doesn't have the greatest contrast, rendering a lot of "easy on the eyes"-themes a little hard to read), I found the hard [[https://github.com/greduan/emacs-theme-gruvbox][gruvbox]] fitting.

#+begin_src emacs-lisp
  ;;(use-package doom-themes
  ;;:init (load-theme 'doom-outrun-electric t))

  ;;(use-package zenburn-theme
  ;;  :config
  ;;  (load-theme 'zenburn t))
  
  (use-package gruvbox-theme
    :config
    (load-theme 'gruvbox-dark-hard t))
#+end_src

** Fonts

These are just fonts from some tutorials. I should make a more informed choice at some point.

#+begin_src emacs-lisp
  (set-face-attribute 'default nil :font "Fira Code Retina" :height 120)
  (set-face-attribute 'fixed-pitch nil :font "Fira Code Retina" :height 120)
  (set-face-attribute 'variable-pitch nil :font "Cantarell" :height 140 :weight 'regular)
#+end_src

** Column Numbering

Ensure that column lines are shown except in org mode, shells and terminals as well as treeviews.

#+begin_src emacs-lisp
  (column-number-mode 1)
  (global-display-line-numbers-mode t)

  ;; Disable line numbers for some modes
  (dolist (mode '(org-mode-hook
  		term-mode-hook
  		shell-mode-hook
  		treemacs-mode-hook
  		eshell-mode-hook
  		pdf-view-mode-hook))
    (add-hook mode (lambda () (display-line-numbers-mode 0))))
#+end_src

** Command Log Mode

The [[https://github.com/lewang/command-log-mode][Command Log Mode]] can display the event and command history of buffers. I use it mostly for learning purposes.

#+begin_src emacs-lisp
  (use-package command-log-mode)
#+end_src

** Rainbow Delimiter

[[https://github.com/Fanael/rainbow-delimiters][Rainbow Delimiters]] color brackets by pairing.

#+begin_src emacs-lisp
  (use-package rainbow-delimiters
    :hook (prog-mode . rainbow-delimiters-mode))
#+end_src

** Icons

Some graphical symbols that are useful are not included out-of-the-box and need to be added manually.

*** All The Icon
With [[https://github.com/domtronn/all-the-icons.el][All The Icons]], we can access a sizable set of general purpose icons.

#+begin_src emacs-lisp
  (use-package all-the-icons
    :if (display-graphic-p))
#+end_src

Using it requires to run `M-x all-the-icons-install-fonts` once after installation.

** Dashboard

The [[https://github.com/emacs-dashboard/dashboard][Dashboard]] package displays a customizable dashboard on startup.

#+begin_src emacs-lisp
  (use-package dashboard
    :config
    (setq dashboard-banner-logo-title "Welcome")
    (setq dashboard-startup-banner "~/.emacs.d/logos/emax.png")
    (setq dashboard-center-content t)
    (setq dashboard-vertical-center-content t)
    (setq dashboard-items '((recents . 5)
  			  (bookmarks . 5)
  			  (projects . 5)
  			  (agenda . 5)
  			  (registers . 5)))
    (setq dashboard-navigation-cycle t)
    (setq dashboard-item-shortcuts '((recents   . "r")
                                     (bookmarks . "m")
                                     (projects  . "p")
                                     (agenda    . "a")
                                     (registers . "e")))
    (setq dashboard-display-icons-p t)
    (setq dashboard-icon-type 'nerd-icons)
    (setq dashboard-set-heading-icons t)
    (setq dashboard-set-file-icons t)
    (dashboard-setup-startup-hook))
#+end_src


* File Management

Emacs can also function as a powerful file manager.

** Dired

Nothing interesting here. In newer Emacs versions, [[https://www.gnu.org/software/emacs/manual/html_node/emacs/Dired.html][dired]] is already included. I just use it with default configurations right now, so the following code doesn't really do anything yet. It's just a placeholder.

#+begin_src emacs-lisp
  (use-package dired
    :ensure nil)
#+end_src


* Keybindings

Emacs is all about keybindings. So this is an important sections!

#+begin_src emacs-lisp
  (global-set-key (kbd "<escape>") 'keyboard-escape-quit)
  (global-set-key (kbd "M-o") 'other-window)  
#+end_src

** General

For custom key definitions, the [[https://github.com/noctuid/general.el][General]] provides a very convenient interface. I use `C-q` as a leader key for my custom commands.

#+begin_src emacs-lisp
  (use-package general
    :config
    (general-create-definer max/leader-keys
      :keymaps 'override
      :prefix "C-q")

    (max/leader-keys
      "t" '(:ignore t :which-key "toggles")
      "c" '(org-capture :which-key "capture template")))
#+end_src

** Hydra

[[https://github.com/abo-abo/hydra][Hydra]] is a wonderful interface for families of keybindings.

#+begin_src emacs-lisp
  (use-package hydra)

  (defhydra hydra-text-scale (:timeout 4)
    "scale text"
    ("j" text-scale-increase "in")
    ("k" text-scale-decrease "out")
    ("f" nil "finished" :exit t))

  (max/leader-keys
    "ts" '(hydra-text-scale/body :which-key "scale text"))
#+end_src


* UI Configuration

The number of ways in which the Emacs UI can be configured can not by known by mortals...

#+begin_src emacs-lisp
  (setq display-buffer-alist '(("\\`\\*e?shell" display-buffer-pop-up-window)
                               ("\\`\\*shell" display-buffer-pop-up-window)
                               ("\\`\\*term" display-buffer-pop-up-window)))
  
  (with-eval-after-load 'ispell
     (remove-hook 'completion-at-point-functions
                  #'ispell-completion-at-point))
#+end_src

** Modeline

[[https://github.com/seagle0128/doom-modeline][doom-modeline]]

#+begin_src emacs-lisp
  (use-package doom-modeline
    :init (doom-modeline-mode 1)
    :custom ((doom-modeline-height 7)))
#+end_src

** Which Key

To better explore and remember keybindings, we can see ... with the [[https://github.com/justbur/emacs-which-key][which-key]] package.

#+begin_src emacs-lisp
  (use-package which-key
    :init (which-key-mode)
    :diminish which-key-mode
    :config
    (setq which-key-idle-delay 0.3))
#+end_src

** Ivy

On [[https://github.com/abo-abo/swiper#ivy][Ivy]]

#+begin_src emacs-lisp
  (use-package ivy
    :diminish
    :bind (("C-s" . swiper)
           :map ivy-minibuffer-map
           ("TAB" . ivy-alt-done)
           ("C-l" . ivy-alt-done)
           ("C-j" . ivy-next-line)
           ("C-k" . ivy-previous-line)
           :map ivy-switch-buffer-map
           ("C-k" . ivy-previous-line)
           ("C-l" . ivy-done)
           ("C-d" . ivy-switch-buffer-kill)
           :map ivy-reverse-i-search-map
           ("C-k" . ivy-previous-line)
           ("C-d" . ivy-reverse-i-search-kill))
    :config
    (setq ivy-use-selectable-prompt t
          ivy-extra-directories nil
  	ivy-use-history t)
    (ivy-mode 1))

  (use-package ivy-prescient
    :after ivy
    :config
    (ivy-prescient-mode 1)
    (prescient-persist-mode 1))

  (use-package ivy-rich
    :init
    (ivy-rich-mode 1))
#+end_src

** Counsel

[[https://github.com/abo-abo/swiper#counsel][Counsel]]

#+begin_src emacs-lisp
  (use-package counsel
    :bind (("M-x" . counsel-M-x)
           ("C-x b" . counsel-ibuffer)
           ("C-x C-f" . counsel-find-file)
           :map minibuffer-local-map
           ("C-r" . 'counsel-minibuffer-history))
    :config
    (setq counsel-find-file-ignore-regexp
        (rx (or (seq string-start "#" (* any) "#" string-end)
                (seq (* any) "~" string-end)
                (seq (* any) ".swp" string-end)
                (seq (* any) ".tmp" string-end)))))
#+end_src

** Helpful

[[https://github.com/Wilfred/helpful][Helpful]]

#+begin_src emacs-lisp
  (use-package helpful
    :custom
    (counsel-describe-function-function #'helpful-callable)
    (counsel-describe-variable-function #'helpful-variable)
    :bind
    ([remap describe-function] . counsel-describe-function)
    ([remap describe-command] . helpful-command)
    ([remap describe-variable] . counsel-describe-variable)
    ([remap describe-key] . helpful-key))
#+end_src


* Org Mode

The infamous [[https://orgmode.org/][Org Mode]] is arguably the best way to organize absolutely anything!

** Appearance

#+begin_src emacs-lisp
  (defun max/org-remove-ispell-capf ()
  (setq-local completion-at-point-functions
              (remove #'ispell-completion-at-point
                      completion-at-point-functions)))

  (defun max/org-mode-setup ()
    (org-indent-mode)
    (variable-pitch-mode 1)
    (auto-fill-mode 0)
    (visual-line-mode 1)
    (max/org-remove-ispell-capf))

  (use-package org
    :hook (org-mode . max/org-mode-setup)
    :config
    (setq org-ellipsis " ▾"
  	org-agenda-start-with-log-mode t
  	org-log-done 'time
  	org-log-into-drawer t
  	org-hide-emphasis-markers t
  	org-startup-folded t
  	org-hide-drawer-startup t
  	org-agenda-files
  	'("~/Nextcloud/Documents/org-files/tasks.org"
  	  "~/Nextcloud/Documents/org-files/habits.org"))
    (require 'org-habit)
    (add-to-list 'org-modules 'org-habit)
    (setq org-habit-graph-column 60)
    :custom
    (setq org-format-latex-options (plist-put org-format-latex-options :scale 1.3))
    (setq org-preview-latex-default-process 'dvisvgm))
  ;; (use-package org-bullets
  ;;   :after org
  ;;   :hook (org-mode . org-bullets-mode))

  ;; (font-lock-add-keywords 'org-mode
  ;; 			'(("^ *\\([-]\\) "
  ;; 			  (0 (prog1 () (compose-region (match-beginning 1)(match-end 1) "•"))))))

  (with-eval-after-load 'org-faces (dolist (face '((org-level-1 . 1.2)
  	        (org-level-2 . 1.1)
  		(org-level-3 . 1.05)
  		(org-level-4 . 1.0)
  		(org-level-5 . 1.1)
  		(org-level-6 . 1.1)
  		(org-level-7 . 1.1)
  		(org-level-8 . 1.1)))
  	      (set-face-attribute (car face) nil :font "Cantarell" :weight 'regular :height (cdr face)))
    (set-face-attribute 'org-block nil :foreground nil :inherit 'fixed-pitch)
    (set-face-attribute 'org-code nil :inherit '(shadow fixed-pitch))
    (set-face-attribute 'org-hide nil :inherit 'fixed-pitch)
    (set-face-attribute 'org-verbatim nil :inherit '(shadow fixed-pitch))
    (set-face-attribute 'org-special-keyword nil :inherit '(font-lock-comment-face fixed-pitch))
    (set-face-attribute 'org-meta-line nil :inherit '(font-lock-comment-face fixed-pitch))
    (set-face-attribute 'org-checkbox nil :inherit 'fixed-pitch)
    (set-face-attribute 'org-table nil :inherit 'fixed-pitch))

  (defun max/org-mode-visual-fill ()
    (setq visual-fill-column-width 100
  	visual-fill-column-center-text t)
    (visual-fill-column-mode 1))

  (use-package visual-fill-column
    :hook (org-mode . max/org-mode-visual-fill))

  (remove-hook 'completion-at-point-functions
             #'ispell-completion-at-point)
#+end_src

*** Org Modern

#+begin_src emacs-lisp
  (use-package org-modern
    :hook (org-mode . org-modern-mode))
#+end_src

** Tasks, Agendas and Tags

#+begin_src emacs-lisp
  (setq org-todo-keywords
      '((sequence "TODO(t)" "NEXT(n)" "|" "DONE(d!)")
        (sequence "BACKLOG(b)" "PLAN(p)" "READY(r)" "ACTIVE(a)" "REVIEW(v)" "WAIT(w@/!)" "HOLD(h)" "|" "COMPLETED(c)" "CANC(k@)")))


  (require 'org-habit)
    (add-to-list 'org-modules 'org-habit)
    (setq org-habit-graph-column 60)

  ;; Save Org buffers after refiling!
  (advice-add 'org-refile :after 'org-save-all-org-buffers)

  (setq org-tag-alist
      '((:startgroup)
         ; Put mutually exclusive tags here
         (:endgroup)
         ("@errand" . ?E)
         ("@home" . ?H)
         ("@work" . ?W)
         ("agenda" . ?a)
         ("planning" . ?p)
         ("publish" . ?P)
         ("batch" . ?b)
         ("note" . ?n)
         ("idea" . ?i)))

  ;; Configure custom agenda views
  (setq org-agenda-custom-commands
     '(("d" "Dashboard"
       ((agenda "" ((org-deadline-warning-days 7)))
        (todo "NEXT"
          ((org-agenda-overriding-header "Next Tasks")))
        (tags-todo "agenda/ACTIVE" ((org-agenda-overriding-header "Active Projects")))))

      ("n" "Next Tasks"
  v     ((todo "NEXT"
          ((org-agenda-overriding-header "Next Tasks")))))

      ("W" "Work Tasks" tags-todo "+work-email")

      ;; Low-effort next actions
      ("e" tags-todo "+TODO=\"NEXT\"+Effort<15&+Effort>0"
       ((org-agenda-overriding-header "Low Effort Tasks")
        (org-agenda-max-todos 20)
        (org-agenda-files org-agenda-files)))

      ("w" "Workflow Status"
       ((todo "WAIT"
              ((org-agenda-overriding-header "Waiting on External")
               (org-agenda-files org-agenda-files)))
        (todo "REVIEW"
              ((org-agenda-overriding-header "In Review")
               (org-agenda-files org-agenda-files)))
        (todo "PLAN"
              ((org-agenda-overriding-header "In Planning")
               (org-agenda-todo-list-sublevels nil)
               (org-agenda-files org-agenda-files)))
        (todo "BACKLOG"
              ((org-agenda-overriding-header "Project Backlog")
               (org-agenda-todo-list-sublevels nil)
               (org-agenda-files org-agenda-files)))
        (todo "READY"
              ((org-agenda-overriding-header "Ready for Work")
               (org-agenda-files org-agenda-files)))
        (todo "ACTIVE"
              ((org-agenda-overriding-header "Active Projects")
               (org-agenda-files org-agenda-files)))
        (todo "COMPLETED"
              ((org-agenda-overriding-header "Completed Projects")
               (org-agenda-files org-agenda-files)))
        (todo "CANC"
              ((org-agenda-overriding-header "Cancelled Projects")
               (org-agenda-files org-agenda-files)))))))
#+end_src

** Templates

#+begin_src emacs-lisp
  (defvar my-org-language-directory
    "~/Nextcloud/Documents/org-files/languages/")

  (defvar my-org-last-language nil)

  (defun my-org-language-files ()
    (mapcar
      (lambda (file)
      (file-name-base file))
    (directory-files
      (expand-file-name my-org-language-directory)
      t
      "\\.org\\'")))

  (defun my-org-select-language ()
    (let* ((langs (my-org-language-files))
         (default (or my-org-last-language
                      (car langs)))
         (choice
          (completing-read
           "Language: "
           langs
           nil
           t
           nil
           nil
           default)))
    (setq my-org-last-language choice)
      choice))

  (defun my-org-capture-anki-basic ()
    (let* ((lang (my-org-select-language))
           (file (expand-file-name
                  (concat lang ".org")
                  my-org-language-directory)))
      (org-capture-set-target-location
       `(file+headline ,file "Basics"))))
  
  (setq org-capture-templates
      `(("t" "Tasks / Projects")
        ("tt" "Task" entry (file+olp "~/Nextcloud/Documents/org-files/tasks.org" "Inbox")
             "* TODO %?\n  %U\n  %a\n  %i" :empty-lines 1)

        ("j" "Journal Entries")
        ("jj" "Journal" entry
             (file+olp+datetree "~/Nextcloud/Documents/org-files/journal.org")
             "\n* %<%I:%M %p> - Journal :journal:\n\n%?\n\n"
             ;; ,(dw/read-file-as-string "~/Notes/Templates/Daily.org")
             :clock-in :clock-resume
             :empty-lines 1)
        ("jm" "Meeting" entry
             (file+olp+datetree "~/Nextcloud/Documents/org-files/journal.org")
             "* %<%I:%M %p> - %a :meetings:\n\n%?\n\n"
             :clock-in :clock-resume
             :empty-lines 1)

        ("v" "Vocabulary")
        ("vb" "Basic" entry (function my-org-capture-anki-basic)
  	 "* %^{Front}\n:PROPERTIES:\n:ANKI_NOTE_TYPE: Basic\n:END:\n\n%^{Back}\n\n")
        
        ("w" "Workflows")
        ("we" "Checking Email" entry (file+olp+datetree "~/Nextcloud/Documents/org-files/journal.org")
             "* Checking Email :email:\n\n%?" :clock-in :clock-resume :empty-lines 1)

        ("m" "Metrics Capture")
        ("mw" "Weight" table-line (file+headline "~/Nextcloud/Documents/org-files/metrics.org" "Weight")
         "| %U | %^{Weight} | %^{Notes} |" :kill-buffer t)
        ("e" "EWW article"
             entry
             (file "~/Nextcloud/Documents/org-files/web.org")
             "* %a\n:PROPERTIES:\n:URL: %u\n:END:\n\n%?"
             :empty-lines 1)))

  (require 'org-tempo)

  (add-to-list 'org-structure-template-alist '("sh" . "src shell"))
  (add-to-list 'org-structure-template-alist '("el" . "src emacs-lisp"))
  (add-to-list 'org-structure-template-alist '("py" . "src python"))
  (add-to-list 'org-structure-template-alist '("rs" . "src rust"))
#+end_src

** Babel

#+begin_src emacs-lisp
  (org-babel-do-load-languages
   'org-babel-load-languages
   '((emacs-lisp . t)
     (python . t)
     (mermaid t)))
#+end_src

*** Tangling

#+begin_src emacs-lisp
  (defun max/org-babel-tangle-config ()
    (when (string-equal (buffer-file-name)
  		      (expand-file-name "~/Documents/Projects/dotfiles/.emacs.d/config.org"))
      (let ((org-confirm-babel-evaluate nil))
        (org-babel-tangle))))

  (add-hook 'org-mode-hook (lambda () (add-hook 'after-save-hook #'max/org-babel-tangle-config)))
#+end_src

*** Mermaid

#+begin_src emacs-lisp
  (use-package ob-mermaid
    :config
    (setq ob-mermaid-default-config-file "~/.config/mermaid/mermaid-config.js"))
#+end_src

** Treeslide

#+begin_src emacs-lisp
  (use-package org-tree-slide
    :custom
    (org-image-actual-width nil))
#+end_src

** Org Roam

#+begin_src emacs-lisp
  (defun org-roam-gaph--view (file)
    (find-file file))

  (use-package org-roam
    :custom
    (org-roam-directory "~/Nextcloud/Documents/org-files/roam")
    :bind (("C-c n l" . org-roam-buffer-toggle)
           ("C-c n f" . org-roam-node-find)
           ("C-c n g" . org-roam-graph)
           ("C-c n i" . org-roam-node-insert)
           ("C-c n c" . org-roam-capture)
           ;; Dailies
           ("C-c n j" . org-roam-dailies-capture-today)
  	 :map org-mode-map
  	 ("C-M-i" . completion-at-point))
    :config
    (setq org-roam-completion-everywhere t)
    (setq org-roam-graph-viewer #'org-roam-graph--view)
    (org-roam-db-autosync-mode))
#+end_src

*** Org Roam UI

#+begin_src emacs-lisp
    (use-package websocket
      :after org-roam)

  (use-package org-roam-ui
      :after org-roam
      :config
      (setq org-roam-ui-sync-theme t
            org-roam-ui-follow t
            org-roam-ui-update-on-save t
            org-roam-ui-open-on-start t))
#+end_src

** Org Eww

#+begin_src emacs-lisp
  (require 'org-eww)
#+end_src

** Org Fragtog
With [[https://github.com/io12/org-fragtog][Fragtog]], inline LaTeX renders on exiting an expression with the cursor.

#+begin_src emacs-lisp
  (use-package org-fragtog
    :hook (org-mode-hook . org-fragtog-mode))
#+end_src


* Development

Configurations for everything coding-related.

** LSP

No modern code editor is complete without prober LSP (Language Server Protocol) support for all or fancy debugging, autocompletion and so on. This is exactly what  [[https://github.com/emacs-lsp/lsp-mode][lsp-mode]] provides.

#+begin_src emacs-lisp
  (defun efs/lsp-mode-setup ()
    (setq lsp-headerline-breadcrumb-segments '(path-up-to-project file symbols))
    (lsp-headerline-breadcrumb-mode))

  (use-package lsp-mode
    :commands (lsp lsp-deferred)
    :hook (lsp-mode . efs/lsp-mode-setup)
    :init
    (setq lsp-keymap-prefix "C-c l")
    :config
    (lsp-enable-which-key-integration t)
    :custom
    ;; what to use when checking on-save. "check" is default, I prefer clippy
    (lsp-rust-analyzer-cargo-watch-command "clippy")
    (lsp-eldoc-render-all t)
    (lsp-idle-delay 0.6)
    ;; enable / disable the hints as you prefer:
    (lsp-inlay-hint-enable t)
    ;; These are optional configurations. See https://emacs-lsp.github.io/lsp-mode/page/lsp-rust-analyzer/#lsp-rust-analyzer-display-chaining-hints for a full list
    (lsp-rust-analyzer-display-lifetime-elision-hints-enable "skip_trivial")
    (lsp-rust-analyzer-display-chaining-hints t)
    (lsp-rust-analyzer-display-lifetime-elision-hints-use-parameter-names nil)
    (lsp-rust-analyzer-display-closure-return-type-hints t)
    (lsp-rust-analyzer-display-parameter-hints nil)
    (lsp-rust-analyzer-display-reborrow-hints nil))

  (use-package lsp-ui
    :hook (lsp-mode . lsp-ui-mode)
    :custom
    (lsp-ui-peek-always-show t)
    (lsp-ui-sideline-show-hover t)
    (lsp-ui-doc-enable nil))

  (use-package lsp-treemacs
    :after lsp)

  (use-package lsp-ivy)

  (max/leader-keys
    "d" '(lsp-ui-doc-show :which-key "show symbol doc"))
#+end_src

** Company Mode
For autocompletion in lsp-mode, I use [[https://github.com/company-mode/company-mode][Company]] (*comp* lete *any* thing).

#+begin_src emacs-lisp
  (use-package company
    :after lsp-mode
    :hook (lsp-mode . company-mode)
    :bind (:map company-active-map
  	  ("<tab>" . company-complete-selection))
          (:map lsp-mode-map
  	  ("<tab>" . company-indent-or-complete-common))
    :custom
    (company-minimum-prefix-length 1)
    (company-idle-delay 0.0)
    (company-backends '(company-capf company-files company-keywords)))
  
  (use-package company-box
    :hook (company-mode . company-box-mode))
#+end_src

** Projectile

[[https://github.com/bbatsov/projectile][Projectile]] for project interactions.

#+begin_src emacs-lisp
  (use-package projectile
    :diminish projectile-mode
    :config (projectile-mode)
    :bind-keymap
    ("C-c p" . projectile-command-map)
    :init
    (when (file-directory-p "~/Documents/Projects")
      (setq projectile-project-search-path '("~/Documents/Projects")))
    (setq projectile-switch-project-action #'projectile-dired))

  (use-package counsel-projectile
    :config (counsel-projectile-mode))
#+end_src

** Magit

[[https://magit.vc/][Magit]] (of which the opinions on how to pronounce it vary) is amazing git porcelain!

#+begin_src emacs-lisp
  (use-package magit
    :custom
    (magit-display-buffer-function #'magit-display-buffer-same-window-except-diff-v1))
#+end_src

*** Ediff

Configure how Magit handles diffs.

#+begin_src emacs-lisp
  (setq magit-ediff-dwim-show-on-hunks t)
  (custom-set-variables '(ediff-split-window-function (quote split-window-horizontally)))
#+end_src

** Language

For each language we code in, we need to set up the appropriate [[LSP]] configurations.

*** Emacs Lisp

Due to Emacs inherent Lisp nature, the elisp-mode is naturally shipped with vanilla Emacs.

#+begin_src emacs-lisp
  (use-package elisp-mode
    :ensure nil
    :hook ((emacs-lisp-mode . flymake-mode)
           (emacs-lisp-mode . eldoc-mode)))
#+end_src

*** Python

[[https://github.com/emacsmirror/python-mode][python-mode]]

#+begin_src emacs-lisp
  (use-package python-mode
    :hook (python-mode . lsp-deferred)
    :config
    (setq python-shell-interpreter "python3"))
#+end_src

*** Rust

[[https://github.com/rust-lang/rust-mode][rust-mode]]

#+begin_src emacs-lisp
  (use-package rustic
  :ensure
  :bind (:map rustic-mode-map
              ("M-j" . lsp-ui-imenu)
              ("M-?" . lsp-find-references)
              ("C-c C-c l" . flycheck-list-errors)
              ("C-c C-c a" . lsp-execute-code-action)
              ("C-c C-c r" . lsp-rename)
              ("C-c C-c q" . lsp-workspace-restart)
              ("C-c C-c Q" . lsp-workspace-shutdown)
              ("C-c C-c s" . lsp-rust-analyzer-status))
  :config
  ;; uncomment for less flashiness
  ;; (setq lsp-eldoc-hook nil)
  ;; (setq lsp-enable-symbol-highlighting nil)
  ;; (setq lsp-signature-auto-activate nil)

  ;; comment to disable rustfmt on save
  (setq rustic-format-on-save t))
#+end_src

#+RESULTS:
: lsp-rust-analyzer-status

*** Bash

Shell script support is also build-in!

#+begin_src emacs-lisp
  (use-package sh-script
    :hook (sh-mode . lsp-deferred))
#+end_src


* Files and Such

Everything regaring file configurations.

** Custom File

I don't really use the interfaces that causes Emacs to persist configurations in the init.el file. But, just in case, the following sets up a different file for these changes (which would otherwise be annoying and conflict with the tangling configuration of this org file).

#+begin_src emacs-lisp
  ;; Use a custom file so that emacs doesn't write in init.el
  (setq custom-file "~/.config/emacs/.emacs.custom")
  (load-file custom-file)
#+end_src

** Refile Targets

In [[Org Mode]], we often refile notes, specifically tasks, to other files. Which files these are need to be set up manually.

#+begin_src emacs-lisp
  (setq org-refile-targets
      '(("archive.org" :maxlevel . 1)
        ("tasks.org" :maxlevel . 1)))
#+end_src


* Applications

Emacs can interface with a variety of other applications.

** Term

[[https://www.gnu.org/software/emacs/manual/html_node/emacs/Terminal-emulator.html][Term]]

#+begin_src emacs-lisp
  (use-package term
    :config
    (setq explicit-shell-file-name "bash")
    (setq term-prompt-regexp "^[^#$%>\n]*[#$%>] *"))
#+end_src

** VTerm

[[https://github.com/akermu/emacs-libvterm][VTerm]]

#+begin_src emacs-lisp
  (use-package vterm
    :commands vterm
    :config
    (setq term-prompt-regexp "^[^#$%>\n]*[#$%>] *")
    (setq vterm-max-scrollback 10000))
#+end_src

** PDF Support
Emacs can open PDFs out of the box but it's not really enough for a proper PDF reader. This is remedied by [[https://github.com/vedang/pdf-tools][pdf-tools.]] Additionally, we can persist the reading state with [[https://github.com/007kevin/pdf-view-restore][pdf-view-restore]].

#+begin_src emacs-lisp
  (use-package pdf-tools
    :init
    (pdf-tools-install)
    :hook
    (pdf-view-mode . pdf-view-roll-minor-mode))

  (use-package pdf-view-restore
    :after pdf-tools
    :config
    (add-hook 'pdf-view-mode-hook 'pdf-view-restore-mode)
    (setq pdf-view-restore-filename (concat user-emacs-directory ".pdf-view-restore")))
#+end_src

** Anki

Obviously, we also want to manage our [[https://github.com/akermu/emacs-libvterm][Anki]] cards with Emacs. A neat package for this, that even integrates with the Anki desktop app, is [[https://github.com/akermu/emacs-libvterm][anki-editor]].

#+begin_src emacs-lisp
  (use-package anki-editor)
#+end_src

** EBDB

[[https://github.com/girzel/ebdb][EBDB]]

#+begin_src emacs-lisp
  (use-package ebdb
    :ensure t
    :defer t
    :init
    (setq ebdb-sources '("~/Nextcloud/emacs/edbd"))
    (setq ebdb-complete-mail t
          ebdb-complete-name t)
    :config
    (setq ebdb-default-window-size 0.3
          ebdb-multiline t)
    (setq ebdb-auto-save-p t)
    (require 'edbd-vcard))
#+end_src

*** Company integration

Company integration for EBDB.

#+begin_src emacs-lisp
  (use-package company-ebdb
    :ensure t
    :after (ebdb company)
    :config
    (add-to-list 'company-backends 'company-ebdb))
#+end_src

*** Ivy-Prescient

Ivy integration for EBDB.

#+begin_src emacs-lisp
  (use-package ivy-prescient
    :after ivy
    :config
    (ivy-prescient-mode 1))
#+end_src


** EWW (Browser)

Emacs has a build-in browser called [[https://www.gnu.org/software/emacs/manual/html_mono/eww.html][EWW]]. It is pretty convenient for some text-heavy pages like wikipedia. But since it can't execute JS, it's quite limited.

#+begin_src emacs-lisp
  (use-package eww
    :commands (eww eww-open-file)
    :init
    (setq eww-search-prefix "https://www.duckduckgo.com/search?q="
          eww-download-directory "~/downloads"
          shr-color-visible-luminance-min 80)

    :config

    ;; ----------------------------
    ;; Search at point / region
    ;; ----------------------------
    (defun max/eww-search-at-point ()
      "Search region or symbol at point."
      (interactive)
      (let ((query
             (cond
              ((use-region-p)
               (buffer-substring-no-properties
                (region-beginning) (region-end)))
              ((thing-at-point 'symbol t))
              (t nil))))
        (if (and query (not (string-blank-p query)))
            (eww query)
          (call-interactively #'eww))))

    ;; ----------------------------
    ;; Force new buffer with C-u
    ;; ----------------------------
    (defun max/eww-new-buffer-advice (orig &rest args)
      (if current-prefix-arg
          (with-temp-buffer (apply orig args))
        (apply orig args)))
    (advice-add 'eww :around #'max/eww-new-buffer-advice)

    ;; ----------------------------
    ;; Auto rename buffers
    ;; ----------------------------
    (add-hook 'eww-mode-hook
              (lambda ()
                (rename-buffer "eww" t)))

    ;; ----------------------------
    ;; Copy URL (simple + reliable)
    ;; ----------------------------
    (defun max/eww-copy-url ()
      "Copy link at point or page URL."
      (interactive)
      (let ((url (or (get-text-property (point) 'shr-url)
                     (eww-current-url))))
        (when url
          (kill-new url)
          (message "Copied: %s" url))))

    ;; ----------------------------
    ;; Toggle images
    ;; ----------------------------
    (defun max/eww-toggle-images ()
      (interactive)
      (setq-local shr-inhibit-images (not shr-inhibit-images))
      (eww-reload)
      (message "Images %s"
               (if shr-inhibit-images "disabled" "enabled")))

    ;; ----------------------------
    ;; Browse current file in EWW
    ;; ----------------------------
    (defun max/eww-browse-file ()
      (interactive)
      (let ((browse-url-browser-function #'eww-browse-url))
        (call-interactively #'browse-url-of-file)))

    ;; ----------------------------
    ;; Core keybindings
    ;; ----------------------------
    (define-key eww-mode-map (kbd "s") #'max/eww-search-at-point)
    (define-key eww-mode-map (kbd "w") #'max/eww-copy-url)
    (define-key eww-mode-map (kbd "I") #'max/eww-toggle-images)
    (define-key eww-mode-map (kbd "h") #'eww-list-histories)
    (define-key eww-mode-map (kbd ":") #'eww)

    ;; Reload
    (define-key eww-mode-map [remap revert-buffer] #'eww-reload)

    ;; Navigation
    (define-key eww-mode-map (kbd "TAB") #'shr-next-link)
    (define-key eww-mode-map (kbd "<backtab>") #'shr-previous-link)
  )

    ;; Default eww key bindings
    ;; |-----------+---------------------------------------------------------------------|
    ;; | Key       | Function                                                            |
    ;; |-----------+---------------------------------------------------------------------|
    ;; | &         | Browse the current URL with an external browser.                    |
    ;; | -         | Begin a negative numeric argument for the next command.             |
    ;; | 0 .. 9    | Part of the numeric argument for the next command.                  |
    ;; | C         | Display a buffer listing the current URL cookies, if there are any. |
    ;; | H         | List the eww-histories.                                             |
    ;; | F         | Toggle font between variable-width and fixed-width.                 |
    ;; | G         | Go to a URL                                                         |
    ;; | R         | Readable mode                                                       |
    ;; | S         | List eww buffers                                                    |
    ;; | d         | Download URL under point to `eww-download-directory'.               |
    ;; | g         | Reload the current page.                                            |
    ;; | q         | Quit WINDOW and bury its buffer.                                    |
    ;; | v         | `eww-view-source'                                                   |
    ;; | w         | `eww-copy-page-url'                                                 |
    ;; |-----------+---------------------------------------------------------------------|
    ;; | b         | Add the current page to the bookmarks.                              |
    ;; | B         | Display the bookmark list.                                          |
    ;; | M-n       | Visit the next bookmark                                             |
    ;; | M-p       | Visit the previous bookmark                                         |
    ;; |-----------+---------------------------------------------------------------------|
    ;; | t         | Go to the page marked `top'.                                        |
    ;; | u         | Go to the page marked `up'.                                         |
    ;; |-----------+---------------------------------------------------------------------|
    ;; | n         | Go to the page marked `next'.                                       |
    ;; | p         | Go to the page marked `previous'.                                   |
    ;; |-----------+---------------------------------------------------------------------|
    ;; | l         | Go to the previously displayed page.                                |
    ;; | r         | Go to the next displayed page.                                      |
    ;; |-----------+---------------------------------------------------------------------|
    ;; | TAB       | Move point to next link on the page.                                |
    ;; | S-TAB     | Move point to previous link on the page.                            |
    ;; |-----------+---------------------------------------------------------------------|
    ;; | SPC       | Scroll up                                                           |
    ;; | DEL/Bkspc | Scroll down                                                         |
    ;; | S-SPC     | Scroll down                                                         |
    ;; |-----------+---------------------------------------------------------------------|
#+end_src

*** EWW LNUM

[[https://github.com/m00natic/eww-lnum][eww-lnum]]

#+begin_src emacs-lisp
  (use-package eww-lnum
    :after eww
    :bind (:map eww-mode-map
                ("f" . eww-lnum-follow)
                ("F" . eww-lnum-universal)))
#+end_src

** Pass

With [[https://github.com/NicolasPetton/pass][pass]], we can easily manage our passwords without leaving Emacs (With the eponymous standard unix password manager [[https://www.passwordstore.org/][pass]]. In case I ever want to use this on non-unix systems like Windows, I need to figure out something else here). Requires [[https://github.com/emacsmirror/password-store][password-store]].

#+begin_src emacs-lisp
(use-package password-store)

(use-package pass
  :after password-store
  :commands (pass))
#+end_src

** Email

Emacs integration for mu.

Requires isync:

#+begin_src shell :tangle no
sudo apt install isync
#+end_src

Before using mu4e, the setup requires an initial sync:

#+begin_src shell :tangle no
  mbsync -a
#+end_src

Requires mu:

#+begin_src shell :tangle no
  sudo apt install mu
  mu init --maildir=~/Mail --my-address=maximilian.muehlbauer@gmx.net
#+end_src

This contains the Emacs integration mu4e already. Therefore, the use-package config below sets ensure to nil. For keeping versions of mu and mu4e in sync, it is better to use the systems package manager.

#+begin_src emacs-lisp
  (use-package mu4e
    :ensure nil
    :load-path "~/mu/mu4e/"
    :config
    (setq mail-user-agent 'mu4e)

    (setq mu4e-mu-binary "~/mu/build/mu/mu")
    (setq mu4e-change-filenames-when-moving t)

    (setq mu4e-update-interval (* 3 60))     ;; Update every 3 minutes
    (setq mu4e-get-mail-command "mbsync -a")
    (setq mu4e-index-lazy-check t)
    (setq mu4e-maildir "~/Mail")
    
    (setq mu4e-drafts-folder "/gmx/Drafts")
    (setq mu4e-sent-folder "/gmx/Sent")
    (setq mu4e-refile-folder "/gmx/Archiv")
    (setq mu4e-trash-folder "/gmx/Trash")

    (setq mu4e-maildir-shortcuts
  	'(("/gmx/INBOX"   . ?i)
  	  ("/gmx/Sent"    . ?s)
  	  ("/gmx/Trash"   . ?t)
  	  ("/gmx/Drafts"  . ?d)
  	  ("/gmx/Archive" . ?a)))

    (setq mu4e-use-fancy-chars t)

    :hook
    ;; tweak the composer
    ((mu4e-compose-mode . (lambda ()
                            (set-fill-column 72)
                            (flyspell-mode)))
     ;; allow for inserting attachments with dired,
     ;;   with `M-x gnus-dired-attach'
     (dired-mode  . turn-on-gnus-dired-mode))

    :bind ;; the Mu4e transient menu
    (("C-c m" . mu4e)))
#+end_src

** TeleAga

This is where the Telegram chat integration goes (not implemented yet). The relevant package is [[https://github.com/zevlg/telega.el][Telega]].

#+begin_src emacs-lisp

#+end_src

** Knowledge Graph Assist

This is a custom package for interfacing with an [[https://arxiv.org/pdf/2603.06290][EpisTwin]]-based AI-assistance framework I'm working on. Commented out until done.

#+begin_src emacs-lisp

;;  (require 'kg)

;;  (setq kg-backend-url "http://localhost:3000")

;;  (setq kg-auto-process nil)

;;  (kg-initialize)

#+end_src
